/*
Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

    22=4, 23=8, 24=16, 25=32
    32=9, 33=27, 34=81, 35=243
    42=16, 43=64, 44=256, 45=1024
    52=25, 53=125, 54=625, 55=3125

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
*/

use std::time::Instant;

pub fn main() {
    let now = Instant::now();
    let mut v: Vec<u128> = vec![];
    let range = 20;
    let mut contained = 0;
    for a in 2..10 {
        for b in 2..range{
            let val = u128::pow(a, b as u32);
            if v.contains(&val){
                println!("Contained: {}", val);
                contained += 1;
            } else {
                v.push(val);
            }
        }
    }
    println!("{:?}", v.len());
    println!("{}", contained);
    println!("{:?}", v);
    println!("Script took {} seconds to run", now.elapsed().as_secs());
}